apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gsaName }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com