spring:

#  datasource:
#    url: jdbc:postgresql://<CLOUD_SQL_CONNECTION_STRING>
#    username: <PROD_DB_USER>
#    password: ${PROD_DB_PASSWORD}

  liquibase:
    contexts: prod

  cloud:
    gcp:
      sql:
        database-name: projectchaos
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}

app:
  frontend-dashboard-url: https://xxxx.zzz