spring:
  datasource:
    url: jdbc:postgresql://<CLOUD_SQL_CONNECTION_STRING>
    username: <PROD_DB_USER>
    password: ${PROD_DB_PASSWORD}
  liquibase:
    contexts: prod

app:
  frontend-dashboard-url: https://xxxx.zzz