spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/project-chaos}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}

  cloud:
    gcp:
      sql:
        enabled: false
      core:
        enabled: false

  liquibase:
    contexts: dev
    drop-first: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        delivery.timeout.ms: 30000
        linger.ms: 0
        request.timeout.ms: 5000
        schema.registry.url: http://localhost:8081
      acks: all

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    sun.rmi: WARN
    javax.management.remote.rmi: WARN

app:
  frontend-dashboard-url: http://localhost:3000/dashboard
  security:
    cookie:
      domain: localhost
      secure: false
  ai:
    number-of-requests-in-time-window-limit: 50
    time-window-in-minutes: 10
