spring:
  application:
    name: Project Chaos

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  data:
    web:
      pageable:
        max-page-size: 50

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-mini
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  metrics:
    tags:
      application: ${spring.application.name}