spring:
  datasource:
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  liquibase:
    contexts: prod

  cloud:
    gcp:
      sql:
        database-name: projectchaos
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}

app:
  frontend-dashboard-url: https://xxxx.zzz