spring:
  datasource:
    # https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/main/resources/application.properties
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  liquibase:
    contexts: prod

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      basic.auth.credentials.source: URL
      security.protocol: SSL
      ssl.truststore.type: PKCS12
      ssl.truststore.location: /cert/truststore.p12
      ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      ssl.keystore.type: PKCS12
      ssl.keystore.location: /cert/keystore.p12
      ssl.keystore.password: ${KEYSTORE_PASSWORD}

  cloud:
    gcp:
      sql:
        database-name: ${PROD_DB_NAME}
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}

app:
  frontend-dashboard-url: https://theprojectchaos.com/dashboard
  security:
    cookie:
      domain: theprojectchaos.com
      secure: true
  ai:
    number-of-requests-in-time-window-limit: 50
    time-window-in-minutes: 10

# check forward-headers-strategy.md in the docs folder
#server:
#  forward-headers-strategy: native