spring:
  application:
    name: social
  security:
    user:
      name: user
      password: pass
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG