spring:
  application:
    name: social
  security:
    user:
      name: user
      password: pass
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
  datasource:
    url: jdbc:postgresql://localhost:5432/social
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
jwt:
  secret: ${SOCIAL_JWT_SECRET}
app:
  frontend-url: http://localhost:3000
  cookie:
    secure: false