spring:
  application:
    name: Project Chaos

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  data:
    web:
      pageable:
        max-page-size: 50

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-mini
      embedding:
        options:
          model: text-embedding-3-small
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 500
        table-name: attachment_embeddings
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      storage:
        enabled: true
        bucket-name: ${GCP_BUCKET_NAME}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      properties:
        delivery.timeout.ms: 30000
        linger.ms: 0
        request.timeout.ms: 5000

jwt:
  secret: ${JWT_SECRET}

tavily:
  api:
    key: ${TAVILY_API_KEY}

storage:
  limits:
    file:
      default: 20971520 # 20MB in bytes
    user:
      default: 314572800  # 300MB in bytes
    project:
      default: 629145600  # 600MB in bytes

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  metrics:
    tags:
      application: ${spring.application.name}

app:
  kafka:
    topic:
      attachment-vectorization-requested: attachment-vectorization-requested
    attachment-vectorization-max-retry-count: 12