spring:
  application:
    name: Project Chaos

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  data:
    web:
      pageable:
        max-page-size: 50

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-mini
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      storage:
        enabled: true
        bucket-name: ${GCP_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}

tavily:
  api:
    key: ${TAVILY_API_KEY}

storage:
  limits:
    file:
      default: 20971520 # 20MB in bytes
    user:
      default: 314572800  # 300MB in bytes
    project:
      default: 629145600  # 600MB in bytes

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  metrics:
    tags:
      application: ${spring.application.name}