# Container image configuration
image:
  repository: europe-central2-docker.pkg.dev/project-chaos-459521/project-chaos-docker-registry/project-chaos-backend
  pullPolicy: Always
  tag: "latest"

# Override chart name
nameOverride: ""
fullnameOverride: ""

# Pod configuration
podAnnotations: {}
podLabels: {}

# Security context
podSecurityContext: {}
securityContext: {}

# Resources limits
resources:
  requests:
    cpu: 380m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http

gcp:
  projectId: project-chaos-459521

serviceAccount:
  name: project-chaos-ksa
  # Nazwa konta serwisowego w Google Cloud (GSA), pod które podszywa się KSA
  gsaName: project-chaos-sa
