name: CD - Docker build & push to GAR

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # only tags in format of x.y.z

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract tag version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker auth to GAR
        uses: 'docker/login-action@v3'
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key
          # secret in github project GCP_ARTIFACT_REGISTRY_KEY = JSON from GCP SA with artifact registry writer role
          password: ${{ secrets.GCP_ARTIFACT_REGISTRY_KEY }}

      - name: Build Docker image
        run: |
          docker build -t project-chaos-backend .

      - name: Tag Docker image
        run: |
          docker tag project-chaos-backend:latest europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REGISTRY_NAME }}/project-chaos-backend:${{ env.VERSION }}

      - name: Push Docker image to GAR
        run: |
          docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REGISTRY_NAME }}/project-chaos-backend:${{ env.VERSION }}
